// InstallService — сервис первичной установки Balloo
// Генерация .env, запуск миграций, seed, создание admin-аккаунта, установка флага .installed

import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { randomBytes } from 'crypto';
import bcrypt from 'bcryptjs';

const ROOT_DIR = join(__dirname, '../../..');
const ENV_PATH = join(ROOT_DIR, '.env');
const INSTALLED_FLAG_PATH = join(ROOT_DIR, '.installed');

// --- Типы ---
export interface InstallConfig {
  // Шаг 1: БД
  dbHost: string;
  dbPort: number;
  dbName: string;
  dbUser: string;
  dbPassword: string;

  // Шаг 2: Redis
  redisHost: string;
  redisPort: number;
  redisPassword: string;

  // Шаг 3: Домены
  domains: Record<string, string>;

  // Шаг 4: Ключи API
  yandexClientId: string;
  yandexClientSecret: string;
  vkClientId: string;
  vkClientSecret: string;
  mailruClientId: string;
  mailruClientSecret: string;
  yookassaShopId: string;
  yookassaApiKey: string;
  minioEndpoint: string;
  minioPort: number;
  minioAccessKey: string;
  minioSecretKey: string;
  minioBucket: string;
  smtpHost: string;
  smtpPort: number;
  smtpUser: string;
  smtpPassword: string;
  smtpFromEmail: string;
  smtpTls: string;
  pushPublicKey: string;
  pushPrivateKey: string;
  pushSubject: string;

  // Шаг 5: Безопасность
  jwtSecret: string;
  jwtAccessTtl: number;
  jwtRefreshTtl: number;
  setupPassword: string;
  adminInstallPassword: string;
}

// --- Проверка установленности ---
export function isInstalled(): boolean {
  return existsSync(INSTALLED_FLAG_PATH);
}

// --- Установка флага ---
export function markInstalled(): void {
  writeFileSync(INSTALLED_FLAG_PATH, new Date().toISOString());
}

// --- Генерация .env ---
export function generateEnvFile(config: InstallConfig): string {
  const env = `# Balloo Messenger — Production Environment
# Generated by InstallWizard on ${new Date().toISOString()}
# ⚠️  НЕ КОМИТЬТЕ В GIT!

# --- PostgreSQL ---
POSTGRES_USER=${config.dbUser}
POSTGRES_PASSWORD=${config.dbPassword}
POSTGRES_DB=${config.dbName}

# --- Redis ---
REDIS_PASSWORD=${config.redisPassword}

# --- JWT ---
JWT_ACCESS_SECRET=${config.jwtSecret}
JWT_REFRESH_SECRET=${config.jwtRefreshTtl}
JWT_ACCESS_EXPIRES_IN=${config.jwtAccessTtl}
JWT_REFRESH_EXPIRES_IN=${config.jwtRefreshTtl}

# --- Server ---
SERVER_PORT=3000
SERVER_HOST=0.0.0.0
NODE_ENV=production

# --- CORS ---
CORS_ORIGIN=${config.domains['balloo.su'] || 'https://balloo.su'}

# --- OAuth — Yandex ID ---
YANDEX_CLIENT_ID=${config.yandexClientId}
YANDEX_CLIENT_SECRET=${config.yandexClientSecret}
YANDEX_REDIRECT_URI=${config.domains['balloo.su'] || 'https://balloo.su'}/api/auth/oauth/yandex-callback

# --- OAuth — VK ID ---
VK_CLIENT_ID=${config.vkClientId}
VK_CLIENT_SECRET=${config.vkClientSecret}
VK_REDIRECT_URI=${config.domains['balloo.su'] || 'https://balloo.su'}/api/auth/oauth/vk/callback

# --- OAuth — Mail.ru ID ---
MAILRU_CLIENT_ID=${config.mailruClientId}
MAILRU_CLIENT_SECRET=${config.mailruClientSecret}
MAILRU_REDIRECT_URI=${config.domains['balloo.su'] || 'https://balloo.su'}/api/auth/oauth/mail/callback

# --- Email (SMTP) ---
SMTP_HOST=${config.smtpHost}
SMTP_PORT=${config.smtpPort}
SMTP_USER=${config.smtpUser}
SMTP_PASSWORD=${config.smtpPassword}
SMTP_FROM=${config.smtpFromEmail}
SMTP_TLS=${config.smtpTls || 'false'}

# --- CDN / Storage (MinIO) ---
MINIO_ROOT_USER=balloo-minio
MINIO_ROOT_PASSWORD=${config.minioSecretKey}
MINIO_ENDPOINT=${config.minioEndpoint}
MINIO_PORT=${config.minioPort}
MINIO_BUCKET=${config.minioBucket}
MINIO_USE_SSL=false

# --- Push Notifications (VAPID Web Push) ---
VAPID_PUBLIC_KEY=${config.pushPublicKey}
VAPID_PRIVATE_KEY=${config.pushPrivateKey}
VAPID_SUBJECT=${config.pushSubject}

# --- Payments (ЮKassa — ЗАГЛУШКА) ---
# В v1: Донаты только по СБП (+79122023035, QR-код)
# ЮKасса будет подключена позже
YOOKASSA_SHOP_ID=${config.yookassaShopId}
YOOKASSA_API_KEY=${config.yookassaApiKey}
YOOKASSA_WEBHOOK_URL=https://api.balloo.su/api/payments/webhook/yookassa

# --- Monitoring ---
PROMETHEUS_ENABLED=false
PROMETHEUS_PORT=9090

# --- Setup ---
ADMIN_INSTALL_PASSWORD=${config.adminInstallPassword}
SETUP_PASSWORD=${config.setupPassword}

# --- Report Issue Channels ---
REPORT_ISSUE_TELEGRAM=https://t.me/balloo_support
REPORT_ISSUE_VK=https://vk.com/balloo_support

# --- File Upload ---
MAX_FILE_SIZE=52428800
ALLOWED_IMAGE_TYPES=image/jpeg,image/png,image/gif,image/webp
ALLOWED_FILE_TYPES=application/pdf,application/zip,application/doc,application/docx
`;

  writeFileSync(ENV_PATH, env);
  return env;
}

// --- Тест подключения к БД ---
export function testDatabase(config: Pick<InstallConfig, 'dbHost' | 'dbPort' | 'dbName' | 'dbUser' | 'dbPassword'>): { ok: boolean; error?: string } {
  try {
    const url = `postgresql://${config.dbUser}:${encodeURIComponent(config.dbPassword)}@${config.dbHost}:${config.dbPort}/${config.dbName}?schema=public`;
    execSync(`npx prisma db pull --url "${url}"`, {
      cwd: join(ROOT_DIR, 'packages/shared'),
      timeout: 10000,
    });
    return { ok: true };
  } catch (err: any) {
    return { ok: false, error: err.stderr?.toString() || err.message || 'Unknown error' };
  }
}

// --- Тест подключения к Redis ---
export function testRedis(config: Pick<InstallConfig, 'redisHost' | 'redisPort' | 'redisPassword'>): { ok: boolean; error?: string } {
  try {
    const cmd = config.redisPassword
      ? `redis-cli -h ${config.redisHost} -p ${config.redisPort} -a ${config.redisPassword} ping`
      : `redis-cli -h ${config.redisHost} -p ${config.redisPort} ping`;
    const result = execSync(cmd, { timeout: 5000 }).toString().trim();
    return result === 'PONG' ? { ok: true } : { ok: false, error: `Redis returned: ${result}` };
  } catch (err: any) {
    return { ok: false, error: err.stderr?.toString() || err.message || 'Unknown error' };
  }
}

// --- Тест домена ---
export function testDomain(url: string): { ok: boolean; error?: string } {
  try {
    execSync(`curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 "${url}"`, { timeout: 10000 });
    return { ok: true };
  } catch {
    return { ok: false, error: `Cannot reach ${url}` };
  }
}

// --- Тест API ключа (заглушка — проверяет формат) ---
export function testApiKey(service: string, key: string): { ok: boolean; error?: string } {
  if (!key || key.length < 3) {
    return { ok: false, error: `Invalid ${service} key format` };
  }
  return { ok: true };
}

// --- Применение настроек ---
export function applyInstallConfig(config: InstallConfig): { ok: boolean; error?: string; steps: string[] } {
  const steps: string[] = [];

  try {
    // 1. Генерация .env
    generateEnvFile(config);
    steps.push('env_generated');

    // 2. Запуск миграций
    try {
      execSync('npx prisma migrate deploy', {
        cwd: join(ROOT_DIR, 'packages/shared'),
        timeout: 30000,
      });
      steps.push('migrations_applied');
    } catch (err: any) {
      steps.push('migrations_failed');
      // Небольшая задержка перед seed
    }

    // 3. Seed
    try {
      execSync('npx prisma db seed', {
        cwd: join(ROOT_DIR, 'packages/shared'),
        timeout: 30000,
      });
      steps.push('seed_applied');
    } catch {
      steps.push('seed_failed');
    }

    // 4. Создание admin-аккаунта (логика в контроллере)
    steps.push('admin_account_created');

    // 5. Установка флага
    markInstalled();
    steps.push('installed_flag_set');

    return { ok: true, steps };
  } catch (err: any) {
    steps.push('error');
    return { ok: false, error: err.stderr?.toString() || err.message || 'Unknown error', steps };
  }
}

// --- Перезапуск сервисов ---
export function restartServices(): { ok: boolean; error?: string } {
  try {
    // PM2
    if (existsSync(join(ROOT_DIR, 'pm2.json'))) {
      execSync('pm2 restart all', { timeout: 10000 });
      return { ok: true };
    }
    // Docker
    if (existsSync(join(ROOT_DIR, 'docker-compose.yml'))) {
      execSync('docker-compose restart', { timeout: 15000 });
      return { ok: true };
    }
    // systemd
    try {
      execSync('systemctl restart balloo-server', { timeout: 10000 });
      return { ok: true };
    } catch {
      return { ok: false, error: 'No supported service manager found (PM2/Docker/systemd)' };
    }
  } catch (err: any) {
    return { ok: false, error: err.stderr?.toString() || err.message || 'Restart failed' };
  }
}

// --- Генерация JWT secret ---
export function generateJwtSecret(): string {
  return randomBytes(64).toString('hex');
}

// --- Хеширование пароля — bcrypt (cost factor 12) ---
export function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, 12);
}
