// InstallService — сервис первичной установки Balloo
// Генерация .env, запуск миграций, seed, создание admin-аккаунта, установка флага .installed

import { execSync } from 'child_process';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { randomBytes, createHash } from 'crypto';

const ROOT_DIR = join(__dirname, '../../..');
const ENV_PATH = join(ROOT_DIR, '.env');
const INSTALLED_FLAG_PATH = join(ROOT_DIR, '.installed');

// --- Типы ---
export interface InstallConfig {
  // Шаг 1: БД
  dbHost: string;
  dbPort: number;
  dbName: string;
  dbUser: string;
  dbPassword: string;

  // Шаг 2: Redis
  redisHost: string;
  redisPort: number;
  redisPassword: string;

  // Шаг 3: Домены
  domains: Record<string, string>;

  // Шаг 4: Ключи API
  yandexClientId: string;
  yandexClientSecret: string;
  vkClientId: string;
  vkClientSecret: string;
  mailruClientId: string;
  mailruClientSecret: string;
  yookassaShopId: string;
  yookassaApiKey: string;
  yandexOsbucket: string;
  yandexOsAccessKey: string;
  yandexOsSecretKey: string;
  yandexOsEndpoint: string;
  minioEndpoint: string;
  minioPort: number;
  minioAccessKey: string;
  minioSecretKey: string;
  minioBucket: string;
  smtpHost: string;
  smtpPort: number;
  smtpUser: string;
  smtpPassword: string;
  smtpFromEmail: string;
  pushPublicKey: string;
  pushPrivateKey: string;
  pushSubject: string;
  grafanaUrl: string;
  grafanaAdminPassword: string;
  yandexMetricaCounterId: string;
  yandexMetricaToken: string;

  // Шаг 5: Безопасность
  jwtSecret: string;
  jwtAccessTtl: number;
  jwtRefreshTtl: number;
  setupPassword: string;
  adminInstallPassword: string;
  corsOrigins: string;
}

// --- Проверка установленности ---
export function isInstalled(): boolean {
  return existsSync(INSTALLED_FLAG_PATH);
}

// --- Установка флага ---
export function markInstalled(): void {
  writeFileSync(INSTALLED_FLAG_PATH, new Date().toISOString());
}

// --- Генерация .env ---
export function generateEnvFile(config: InstallConfig): string {
  const env = `# Balloo Messenger — Environment Configuration
# Generated by InstallWizard on ${new Date().toISOString()}

# ============================================
# PostgreSQL Database
# ============================================
DATABASE_URL=postgresql://${config.dbUser}:${encodeURIComponent(config.dbPassword)}@${config.dbHost}:${config.dbPort}/${config.dbName}?schema=public

# ============================================
# Redis
# ============================================
REDIS_HOST=${config.redisHost}
REDIS_PORT=${config.redisPort}
REDIS_PASSWORD=${config.redisPassword}

# ============================================
# Domains
# ============================================
DOMAIN_BALLOO=${config.domains['balloo.su'] || 'http://localhost:5173'}
DOMAIN_ADMIN=${config.domains['admin.balloo.su'] || 'http://localhost:3001'}
DOMAIN_COMMAND=${config.domains['command.balloo.su'] || 'http://localhost:3002'}
DOMAIN_FEATURES=${config.domains['features.balloo.su'] || 'http://localhost:3003'}
DOMAIN_HISTORY=${config.domains['history.balloo.su'] || 'http://localhost:3004'}
DOMAIN_DOWNLOAD=${config.domains['download.balloo.su'] || 'http://localhost:3005'}
DOMAIN_API=${config.domains['api.balloo.su'] || 'http://localhost:3100'}
DOMAIN_BLOG=${config.domains['blog.balloo.su'] || 'http://localhost:3006'}
DOMAIN_SPECIFITY=${config.domains['specifity.balloo.su'] || 'http://localhost:3007'}
DOMAIN_CDN=${config.domains['cdn.balloo.su'] || 'https://cdn.balloo.su'}

# ============================================
# OAuth — Yandex ID
# ============================================
YANDEX_CLIENT_ID=${config.yandexClientId}
YANDEX_CLIENT_SECRET=${config.yandexClientSecret}
YANDEX_REDIRECT_URI=${config.domains['balloo.su'] || 'http://localhost:5173'}/api/auth/yandex/callback

# ============================================
# OAuth — VK ID
# ============================================
VK_CLIENT_ID=${config.vkClientId}
VK_CLIENT_SECRET=${config.vkClientSecret}
VK_REDIRECT_URI=${config.domains['balloo.su'] || 'http://localhost:5173'}/api/auth/vk/callback

# ============================================
# OAuth — Mail.ru ID
# ============================================
MAILRU_CLIENT_ID=${config.mailruClientId}
MAILRU_CLIENT_SECRET=${config.mailruClientSecret}
MAILRU_REDIRECT_URI=${config.domains['balloo.su'] || 'http://localhost:5173'}/api/auth/mailru/callback

# ============================================
# Payments — YooKassa
# ============================================
YOOKASSA_SHOP_ID=${config.yookassaShopId}
YOOKASSA_API_KEY=${config.yookassaApiKey}

# ============================================
# CDN — Yandex Object Storage
# ============================================
YANDEX_OS_BUCKET=${config.yandexOsbucket}
YANDEX_OS_ACCESS_KEY=${config.yandexOsAccessKey}
YANDEX_OS_SECRET_KEY=${config.yandexOsSecretKey}
YANDEX_OS_ENDPOINT=${config.yandexOsEndpoint}

# ============================================
# CDN — MinIO (fallback)
# ============================================
MINIO_ENDPOINT=${config.minioEndpoint}
MINIO_PORT=${config.minioPort}
MINIO_ACCESS_KEY=${config.minioAccessKey}
MINIO_SECRET_KEY=${config.minioSecretKey}
MINIO_BUCKET=${config.minioBucket}

# ============================================
# SMTP — Postfix
# ============================================
SMTP_HOST=${config.smtpHost}
SMTP_PORT=${config.smtpPort}
SMTP_USER=${config.smtpUser}
SMTP_PASSWORD=${config.smtpPassword}
SMTP_FROM_EMAIL=${config.smtpFromEmail}

# ============================================
# Web Push — VAPID
# ============================================
PUSH_PUBLIC_KEY=${config.pushPublicKey}
PUSH_PRIVATE_KEY=${config.pushPrivateKey}
PUSH_SUBJECT=${config.pushSubject}

# ============================================
# Monitoring — Prometheus + Grafana
# ============================================
GRAFANA_URL=${config.grafanaUrl}
GRAFANA_ADMIN_PASSWORD=${config.grafanaAdminPassword}

# ============================================
# Analytics — Yandex.Metrika
# ============================================
YANDEX_METRIKA_COUNTER_ID=${config.yandexMetricaCounterId}
YANDEX_METRIKA_TOKEN=${config.yandexMetricaToken}

# ============================================
# Security
# ============================================
JWT_SECRET=${config.jwtSecret}
JWT_ACCESS_TTL=${config.jwtAccessTtl}
JWT_REFRESH_TTL=${config.jwtRefreshTtl}
SETUP_PASSWORD=${config.setupPassword}
ADMIN_INSTALL_PASSWORD=${config.adminInstallPassword}
CORS_ORIGINS=${config.corsOrigins}

# ============================================
# Server
# ============================================
PORT=3100
NODE_ENV=production

# ============================================
# Shared
# ============================================
SHARED_PATH=packages/shared
`;

  writeFileSync(ENV_PATH, env);
  return env;
}

// --- Тест подключения к БД ---
export function testDatabase(config: Pick<InstallConfig, 'dbHost' | 'dbPort' | 'dbName' | 'dbUser' | 'dbPassword'>): { ok: boolean; error?: string } {
  try {
    const url = `postgresql://${config.dbUser}:${encodeURIComponent(config.dbPassword)}@${config.dbHost}:${config.dbPort}/${config.dbName}?schema=public`;
    execSync(`npx prisma db pull --url "${url}"`, {
      cwd: join(ROOT_DIR, 'packages/shared'),
      timeout: 10000,
    });
    return { ok: true };
  } catch (err: any) {
    return { ok: false, error: err.stderr?.toString() || err.message || 'Unknown error' };
  }
}

// --- Тест подключения к Redis ---
export function testRedis(config: Pick<InstallConfig, 'redisHost' | 'redisPort' | 'redisPassword'>): { ok: boolean; error?: string } {
  try {
    const cmd = config.redisPassword
      ? `redis-cli -h ${config.redisHost} -p ${config.redisPort} -a ${config.redisPassword} ping`
      : `redis-cli -h ${config.redisHost} -p ${config.redisPort} ping`;
    const result = execSync(cmd, { timeout: 5000 }).toString().trim();
    return result === 'PONG' ? { ok: true } : { ok: false, error: `Redis returned: ${result}` };
  } catch (err: any) {
    return { ok: false, error: err.stderr?.toString() || err.message || 'Unknown error' };
  }
}

// --- Тест домена ---
export function testDomain(url: string): { ok: boolean; error?: string } {
  try {
    execSync(`curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 "${url}"`, { timeout: 10000 });
    return { ok: true };
  } catch {
    return { ok: false, error: `Cannot reach ${url}` };
  }
}

// --- Тест API ключа (заглушка — проверяет формат) ---
export function testApiKey(service: string, key: string): { ok: boolean; error?: string } {
  if (!key || key.length < 3) {
    return { ok: false, error: `Invalid ${service} key format` };
  }
  return { ok: true };
}

// --- Применение настроек ---
export function applyInstallConfig(config: InstallConfig): { ok: boolean; error?: string; steps: string[] } {
  const steps: string[] = [];

  try {
    // 1. Генерация .env
    generateEnvFile(config);
    steps.push('env_generated');

    // 2. Запуск миграций
    try {
      execSync('npx prisma migrate deploy', {
        cwd: join(ROOT_DIR, 'packages/shared'),
        timeout: 30000,
      });
      steps.push('migrations_applied');
    } catch (err: any) {
      steps.push('migrations_failed');
      // Небольшая задержка перед seed
    }

    // 3. Seed
    try {
      execSync('npx prisma db seed', {
        cwd: join(ROOT_DIR, 'packages/shared'),
        timeout: 30000,
      });
      steps.push('seed_applied');
    } catch {
      steps.push('seed_failed');
    }

    // 4. Создание admin-аккаунта (логика в контроллере)
    steps.push('admin_account_created');

    // 5. Установка флага
    markInstalled();
    steps.push('installed_flag_set');

    return { ok: true, steps };
  } catch (err: any) {
    steps.push('error');
    return { ok: false, error: err.stderr?.toString() || err.message || 'Unknown error', steps };
  }
}

// --- Перезапуск сервисов ---
export function restartServices(): { ok: boolean; error?: string } {
  try {
    // PM2
    if (existsSync(join(ROOT_DIR, 'pm2.json'))) {
      execSync('pm2 restart all', { timeout: 10000 });
      return { ok: true };
    }
    // Docker
    if (existsSync(join(ROOT_DIR, 'docker-compose.yml'))) {
      execSync('docker-compose restart', { timeout: 15000 });
      return { ok: true };
    }
    // systemd
    try {
      execSync('systemctl restart balloo-server', { timeout: 10000 });
      return { ok: true };
    } catch {
      return { ok: false, error: 'No supported service manager found (PM2/Docker/systemd)' };
    }
  } catch (err: any) {
    return { ok: false, error: err.stderr?.toString() || err.message || 'Restart failed' };
  }
}

// --- Генерация JWT secret ---
export function generateJwtSecret(): string {
  return randomBytes(64).toString('hex');
}

// --- Хеширование пароля ---
export function hashPassword(password: string): string {
  return createHash('sha256').update(password + process.env.JWT_SECRET || 'default-secret').digest('hex');
}
